export type GuideTopic = {
  id: string;
  title: string;
  answer: string;
};

export type GuideCluster = {
  slug: string;
  title: string;
  shortTitle: string;
  description: string;
  kicker: string;
  hero: string;
  heroAlt: string;
  productIds: string[];
  buyingRules: string[];
  topics: GuideTopic[];
  faq: { question: string; answer: string }[];
};

export const guideClusters: GuideCluster[] = [
  {
    slug: "adventskalender-kaufberatung",
    title: "Adventskalender kaufen: die große Kaufberatung",
    shortTitle: "Kaufberatung",
    description: "Welcher Adventskalender passt zu wem? Budget, Inhalt, Warenwert und Kaufzeitpunkt verständlich erklärt – mit aktuellen Produktvergleichen.",
    kicker: "Besser auswählen statt länger suchen",
    hero: "/guides/001-geschenkefinder.jpg",
    heroAlt: "Verschiedene Adventskalender für unterschiedliche Interessen in einer festlichen Umgebung",
    productIds: ["AK-0001", "AK-0002", "AK-0008"],
    buyingRules: [
      "Erst Empfänger und Nutzungsritual bestimmen, dann eine Produktkategorie wählen.",
      "Preis, Inhalt und dokumentierte Qualität gemeinsam betrachten – nicht nur den angeblichen Warenwert.",
      "Bei saisonalen Artikeln Lieferzeit, Aktualität und Rückgabebedingungen vor dem Kauf prüfen.",
      "Produktbilder und Preise im Vergleich werden, sofern verfügbar, über die Amazon Creators API aktualisiert.",
    ],
    topics: [
      { id: "welcher-passt", title: "Welcher Adventskalender passt zu wem?", answer: "Der passende Kalender orientiert sich weniger an Geschlecht oder Bestsellerlisten als am Alltag der beschenkten Person. Wer morgens Tee trinkt, abends rätselt oder gemeinsam mit Kindern liest, braucht jeweils ein anderes tägliches Ritual. Nutze Interessen, verfügbare Zeit und gewünschte Überraschungsstärke als erste Filter." },
      { id: "vor-bestellung", title: "Darauf solltest du vor der Bestellung achten", answer: "Prüfe Inhalt, Zielgruppe, Mindestalter, Anzahl der Einheiten und die Aktualität der Produktbeschreibung. Bei Marktplatzangeboten können Verkäufer, Lieferzeit und Umfang wechseln. Entscheidend sind deshalb die Angaben auf der aktuellen Produktseite; unsere redaktionellen Daten dienen als verständliche Vorauswahl." },
      { id: "fuer-frauen", title: "Die besten Adventskalender für Frauen", answer: "Gute Empfehlungen entstehen aus Interessen: Beauty, Tee, Bücher, Schmuck, Rätsel oder kreative Projekte. Ein pauschaler Damenkalender ist selten so treffsicher wie ein Kalender, der eine konkrete Gewohnheit aufgreift. Achte bei Kosmetik zusätzlich auf Hauttyp, Duftvorlieben und bekannte Unverträglichkeiten." },
      { id: "fuer-maenner", title: "Die besten Adventskalender für Männer", answer: "Auch hier sollte das Hobby den Ausschlag geben. Werkzeug, Kaffee, Rätsel, Pflege, Kochen oder Bücher können passen; stereotype Füllungen müssen es nicht. Besonders bei Werkzeug- und Genusskalendern lohnt ein Blick darauf, ob die enthaltenen Produkte wirklich nutzbar oder überwiegend Proben sind." },
      { id: "paare", title: "Adventskalender für Paare", answer: "Ein Paarkalender funktioniert am besten, wenn er gemeinsame Zeit schafft. Duelle, Fragen, kleine Aufgaben oder Genussproben bieten mehr Gesprächsanlässe als zwei getrennte Ansammlungen von Kleinigkeiten. Vor dem Kauf sollte klar sein, ob beide täglich teilnehmen möchten und wie viel Zeit ein Türchen beansprucht." },
      { id: "familien", title: "Adventskalender für Familien", answer: "Familienkalender müssen unterschiedliche Altersstufen zusammenbringen. Vorlesegeschichten, gemeinsame Rätsel und kleine Aktivitäten sind häufig geeigneter als Inhalte, die nur ein Kind nutzen kann. Bei Kleinteilen gilt immer die niedrigste Altersfreigabe als Maßstab." },
      { id: "unter-20-euro", title: "Adventskalender unter 20 Euro", answer: "Ein kleines Budget kann gut funktionieren, wenn das Thema präzise gewählt ist. Bücher, Tee, Rätsel und selbst befüllte Modelle bieten oft mehr Nutzwert als sehr günstige Mischkalender. Vergleiche nicht nur die Zahl der Türchen, sondern auch Wiederholungen, Portionsgrößen und Versandkosten." },
      { id: "luxus", title: "Luxus-Adventskalender: Wann lohnt sich der hohe Preis?", answer: "Ein hoher Preis ist nur dann plausibel, wenn Markenqualität, Originalgrößen, besondere Zusammenstellung oder eine wiederverwendbare Verpackung erkennbar sind. Addiere den realistischen Einzelwert vorsichtig und berücksichtige, ob du die Produkte tatsächlich nutzen würdest. Ein behaupteter Warenwert ist keine automatische Ersparnis." },
      { id: "online-oder-laden", title: "Adventskalender online oder im Geschäft kaufen?", answer: "Online ist die Auswahl größer und Produkte lassen sich leichter vergleichen. Im Geschäft kannst du Größe, Verarbeitung und Gewicht unmittelbar einschätzen und sparst Versandrisiken. Bei knappen oder empfindlichen Kalendern ist Abholung oft sinnvoll; bei Spezialinteressen bietet der Onlinekauf meist mehr Auswahl." },
      { id: "kaufzeitpunkt", title: "Wann sollte man einen Adventskalender kaufen?", answer: "Beliebte Spezial- und Markenkalender erscheinen häufig schon im Spätsommer oder Frühherbst. Für eine große Auswahl ist Oktober ein guter Orientierungsmonat; im November steigt das Risiko ausverkaufter Varianten. Nach Weihnachten sinken Preise, doch dann eignet sich der Kauf nur für haltbare Inhalte oder das Folgejahr." },
    ],
    faq: [
      { question: "Wie erkenne ich einen guten Adventskalender?", answer: "An einer klaren Inhaltsbeschreibung, nachvollziehbarer Zielgruppe, transparenten Größenangaben, aktuellen Sicherheitsinformationen und einem Preis, der zum tatsächlichen Nutzwert passt." },
      { question: "Sind teure Adventskalender automatisch besser?", answer: "Nein. Entscheidend ist, wie viele Inhalte zur beschenkten Person passen und ob Qualität, Originalgrößen oder Wiederverwendbarkeit den Mehrpreis rechtfertigen." },
      { question: "Wie aktuell sind die Preise im Vergleich?", answer: "Wenn die Amazon Creators API verbunden und erreichbar ist, werden Angebotspreis und Verfügbarkeit dynamisch geladen. Verbindlich bleibt immer die Anzeige auf Amazon." },
    ],
  },
  {
    slug: "adventskalender-kinder-teenager",
    title: "Adventskalender für Kinder und Teenager",
    shortTitle: "Kinder & Jugendliche",
    description: "Adventskalender nach Alter auswählen: sichere, sinnvolle und wirklich passende Empfehlungen für Kleinkinder, Schulkinder und Teenager.",
    kicker: "Alter, Sicherheit und echter Spielwert",
    hero: "/guides/011-altersgruppen.jpg",
    heroAlt: "Mehrere altersgerechte Adventskalender mit Spiel- und Kreativmaterial",
    productIds: ["AK-0001", "AK-0009", "AK-0017"],
    buyingRules: [
      "Herstellerangaben zum Mindestalter und Warnhinweise haben Vorrang vor Geschenkempfehlungen.",
      "Kleine Teile, Kosmetik und Experimente nur passend zum Entwicklungsstand auswählen.",
      "Ein zusammenhängendes Spiel- oder Lernziel erzeugt meist mehr Wert als 24 lose Kleinigkeiten.",
      "Interessen des Kindes berücksichtigen, nicht nur Alter und Marketingfarbe.",
    ],
    topics: [
      { id: "alter", title: "Welcher Adventskalender eignet sich für welches Alter?", answer: "Unter drei Jahren stehen große, robuste Teile und gemeinsames Öffnen im Vordergrund. Kindergartenkinder profitieren von einfachen Geschichten und Rollenspiel, Schulkinder von Bauen, Rätseln und Experimenten. Teenager wünschen meist ernst genommene Interessen, praktische Produkte oder anspruchsvollere Herausforderungen." },
      { id: "kleinkinder", title: "Die schönsten Adventskalender für Kleinkinder", answer: "Wähle stabile Kalender mit großen Elementen, abgerundeten Formen und klarer Altersfreigabe. Stofftaschen mit selbst ausgewählten Bilderbüchern, Figuren oder gemeinsamen Aktivitäten lassen sich besonders gut anpassen. Süßigkeiten und Kleinteile sollten nicht das Grundkonzept ersetzen." },
      { id: "kindergarten", title: "Adventskalender für Kindergartenkinder", answer: "In diesem Alter sind kurze, sofort verständliche Spielimpulse ideal. Tierfiguren, einfache Bastelideen und fortlaufende Vorlesegeschichten funktionieren gut, wenn eine erwachsene Person begleitet. Zu komplizierte Bauprojekte führen dagegen schnell zu Frust." },
      { id: "grundschule", title: "Adventskalender für Grundschulkinder", answer: "Grundschulkinder können bereits über mehrere Tage sammeln, bauen oder einer Geschichte folgen. Gute Kalender verbinden Erfolgserlebnisse mit steigender Schwierigkeit. Prüfe, ob Anleitung und erforderliche Lesefähigkeit zum Kind passen." },
      { id: "teenager", title: "Adventskalender für Teenager", answer: "Teenager reagieren sensibel auf zu kindliche Gestaltung. Gaming, Pflege, Bücher, Kreativität, Snacks oder ein selbst befüllter Kalender mit kleinen Alltagshelfern wirken persönlicher. Bei Beautyprodukten sind Inhaltsstoffe und Hautverträglichkeit wichtiger als eine große Produktzahl." },
      { id: "ohne-suessigkeiten", title: "Adventskalender ohne Süßigkeiten für Kinder", answer: "Bücher, Bausteine, Rätsel, Bastelmaterial und gemeinsame Gutscheine bieten tägliche Überraschungen ohne Zucker. Besonders nachhaltig sind Inhalte, die am Ende ein vollständiges Spiel oder Projekt ergeben. Berücksichtige trotzdem Materialqualität und mögliche Kleinteile." },
      { id: "paedagogisch", title: "Pädagogisch wertvolle Adventskalender", answer: "Pädagogischer Wert entsteht nicht durch ein Etikett, sondern durch aktives Denken, Gestalten, Erzählen oder gemeinsames Handeln. Der Kalender sollte weder überfordern noch wie Hausaufgaben wirken. Kurze Aufgaben mit sichtbarem Ergebnis halten die Motivation hoch." },
      { id: "experimente", title: "Experimentier-Adventskalender für neugierige Kinder", answer: "Achte auf Altersfreigabe, Schutzbedarf, benötigte Haushaltsmaterialien und den Zeitaufwand pro Versuch. Gute Sets erklären Beobachtungen verständlich und funktionieren mit erwachsener Begleitung. Chemikalien, Hitze oder Strom dürfen nie ohne klare Sicherheitsanleitung eingesetzt werden." },
      { id: "buecher", title: "Bücher-Adventskalender für kleine Leseratten", answer: "Fortlaufende Geschichten schaffen ein ruhiges tägliches Ritual. Prüfe Textmenge, Vorlesealter, Schriftgröße und ob die Handlung religiös, klassisch oder modern geprägt ist. Boxen mit einzelnen Büchern lassen sich später leichter erneut verwenden." },
      { id: "spielzeug", title: "Spielzeug-Adventskalender: Welche Varianten gibt es?", answer: "Figuren, Bausteine, Sammelsets, Rollenspiel und Kreativspiel unterscheiden sich stark. Achte darauf, ob nach dem letzten Türchen ein sinnvoll nutzbares Gesamtset entsteht. Lizenzfiguren können begeistern, sind aber kein Ersatz für solide Verarbeitung und passenden Spielwert." },
    ],
    faq: [
      { question: "Ab welchem Alter ist ein Adventskalender sinnvoll?", answer: "Ein gemeinsames Ritual kann bereits im Kleinkindalter funktionieren. Der konkrete Inhalt muss jedoch ausdrücklich altersgeeignet sein und sollte bei kleinen Kindern begleitet werden." },
      { question: "Sind Spielzeugkalender für Geschwister geeignet?", answer: "Nur wenn das gemeinsame Nutzen vorher geklärt ist. Häufig vermeidet ein Familienkalender mit gemeinsamen Aufgaben Streit besser als einzelne Sammelteile." },
      { question: "Was ist bei Experimentierkalendern wichtig?", answer: "Altersfreigabe, Aufsicht, Schutzmaßnahmen, benötigte Zusatzmaterialien und verständliche Anleitungen sollten vor dem Kauf geprüft werden." },
    ],
  },
  {
    slug: "essen-trinken-adventskalender",
    title: "Essens- und Getränke-Adventskalender im Vergleich",
    shortTitle: "Essen & Trinken",
    description: "Schokolade, Tee, Kaffee, Gewürze und Snacks: So vergleichst du Genuss-Adventskalender nach Geschmack, Zutaten, Menge und Preis.",
    kicker: "24 Genussmomente sinnvoll vergleichen",
    hero: "/guides/021-schokolade.jpg",
    heroAlt: "Schokoladen-Adventskalender mit verschiedenen Pralinen und Kakaofrüchten",
    productIds: ["AK-0008", "AK-0054", "AK-0063"],
    buyingRules: ["Zutatenliste, Allergene und Portionsgrößen vor dem Kauf lesen.", "Bei Getränken Zubereitungssystem und benötigtes Zubehör prüfen.", "Vielfalt ist nur dann ein Vorteil, wenn die Geschmacksrichtungen zur Person passen.", "Haltbarkeit und Lagerung bei frühem Kauf berücksichtigen."],
    topics: [
      { id: "schokolade", title: "Schokoladen-Adventskalender: Sorten, Qualität und Kaufberatung", answer: "Entscheidend sind Kakaoanteil, Zutaten, Füllungen und Stückgewicht. Pralinenkalender benötigen oft kühlere Lagerung als massive Schokolade. Wer bestimmte Sorten nicht mag oder Allergien hat, sollte eine vollständige Inhaltsübersicht höher gewichten als eine luxuriöse Verpackung." },
      { id: "suessigkeiten", title: "Süßigkeiten-Adventskalender abseits klassischer Schokolade", answer: "Fruchtgummi, Karamell, Bonbons und internationale Snacks bringen Abwechslung, können aber viele Wiederholungen enthalten. Vergleiche Nettogewicht, Einzelportionen und Zutaten. Für Kinder sind sehr harte Bonbons oder extrem saure Produkte nicht in jedem Alter geeignet." },
      { id: "tee", title: "Tee-Adventskalender: So findest du die passende Auswahl", answer: "Schwarztee, Grüntee, Kräuter- und Früchtetee haben unterschiedliche Ziehzeiten und Koffeingehalte. Prüfe, ob pro Türchen ein oder mehrere Aufgüsse enthalten sind und ob lose Blätter Zubehör erfordern. Eine ausgewogene Mischung passt eher zu Entdeckern, eine klare Stilrichtung zu Kennern." },
      { id: "kaffee", title: "Kaffee-Adventskalender für Bohnen, Filter und Kapseln", answer: "Das Zubereitungssystem muss exakt passen. Ganze Bohnen bleiben meist aromatischer, benötigen aber eine Mühle; Filterportionen sind unkompliziert, Kapseln maschinengebunden. Röstdatum, Herkunft und Menge pro Portion sind aussagekräftiger als eine lange Liste exotischer Namen." },
      { id: "gewuerze", title: "Gewürz-Adventskalender für Hobbyköche", answer: "Gute Gewürzkalender erklären Verwendung und enthalten ausreichend Menge für mindestens ein Gericht. Mischungen sind bequem, Einzelgewürze vielseitiger. Salzlastige Füllungen und winzige Proben relativieren einen hohen angeblichen Warenwert." },
      { id: "snacks", title: "Snack-Adventskalender mit süßen und herzhaften Überraschungen", answer: "Snackkalender eignen sich für Menschen, die bewusst probieren möchten. Achte auf das Verhältnis von süß zu herzhaft, Portionsgrößen, Herkunft und Wiederholungen. Internationale Produkte benötigen eine verständliche Allergenkennzeichnung." },
      { id: "vegan", title: "Vegane Adventskalender", answer: "Die Bezeichnung vegan sollte durch Zutaten und Kennzeichnung nachvollziehbar sein. Spurenhinweise sind für Allergiker gesondert zu bewerten. Bei Schokolade beeinflussen Kakaoanteil, Pflanzenfette und Füllungen Geschmack und Qualität erheblich." },
      { id: "glutenfrei", title: "Glutenfreie Adventskalender: Darauf müssen Betroffene achten", answer: "Für Menschen mit Zöliakie reicht eine augenscheinlich glutenfreie Rezeptur nicht immer aus. Prüfe eindeutige Kennzeichnung, Spurenhinweise und Informationen zur Herstellung. Im Zweifel ist eine direkt bestätigte Herstellerangabe wichtiger als eine Händlerkategorie." },
      { id: "zuckerarm", title: "Adventskalender ohne Zucker und zuckerarme Alternativen", answer: "Zuckerfrei kann Süßstoffe, Zuckeralkohole oder konzentrierte Fruchtsüße bedeuten. Manche Ersatzstoffe wirken in größeren Mengen abführend. Tee, Gewürze, Nüsse oder Aktivitätskalender sind oft unkompliziertere Alternativen zu stark verarbeiteten Ersatzsüßigkeiten." },
      { id: "alkohol", title: "Alkoholische Adventskalender verantwortungsvoll auswählen", answer: "Diese Kalender gehören ausschließlich in die Hände Erwachsener. Prüfe Flaschengrößen, Alkoholgehalt, Herkunft und ob Verkostung oder bloße Menge im Mittelpunkt steht. Eine alkoholfreie Alternative und bewusste Pausentage machen das Ritual verantwortungsvoller." },
    ],
    faq: [
      { question: "Wie vergleicht man den Preis von Genusskalendern?", answer: "Nutze Nettogewicht, Portionszahl, Qualität der Zutaten und realistische Einzelpreise. Die Verpackung allein ist kein Qualitätsmerkmal." },
      { question: "Wo finde ich verbindliche Allergenangaben?", answer: "Auf der Produktverpackung und in den aktuellen Hersteller- beziehungsweise Händlerangaben. Unsere redaktionelle Einordnung ersetzt diese Prüfung nicht." },
      { question: "Kann man Lebensmittelkalender früh kaufen?", answer: "Ja, wenn Mindesthaltbarkeit und Lagerbedingungen passen. Schokolade, Kaffee und empfindliche Füllungen sollten trocken, geruchsneutral und temperaturstabil gelagert werden." },
    ],
  },
  {
    slug: "beauty-wellness-adventskalender",
    title: "Beauty- und Wellness-Adventskalender richtig vergleichen",
    shortTitle: "Beauty & Wellness",
    description: "Beauty, Make-up, Pflege, Parfum und Wellness: Inhalte, Originalgrößen, Hautverträglichkeit und Warenwert verständlich bewerten.",
    kicker: "Pflege statt bloßer Probenmenge",
    hero: "/guides/031-beauty-warenwert.jpg",
    heroAlt: "Beauty-Adventskalender mit Pflegeprodukten und Vergleichshilfen",
    productIds: ["AK-0002", "AK-0013", "AK-0027"],
    buyingRules: ["Hauttyp, Duftvorlieben und bekannte Allergien zuerst berücksichtigen.", "Originalgrößen, Reisegrößen und Sachets getrennt bewerten.", "Ungeöffnete Haltbarkeit und Öffnungsdauer der Produkte beachten.", "Warenwert nur für Produkte ansetzen, die tatsächlich genutzt werden."],
    topics: [
      { id: "lohnt-sich", title: "Beauty-Adventskalender: Lohnt sich der Inhalt wirklich?", answer: "Ein Beauty-Kalender lohnt sich, wenn ein großer Teil der Marken, Farbtöne und Produktarten zur Person passt. Addiere den realistischen Einzelwert, nicht unverbindliche Fantasiepreise. Viele kleine Sachets erzeugen zwar Stückzahl, aber nur wenig Nutzungsdauer." },
      { id: "make-up", title: "Make-up-Adventskalender richtig vergleichen", answer: "Farbtöne, Hautunterton und bevorzugte Produktarten entscheiden über den Nutzen. Neutrale Farben sind vielseitiger, aber nicht automatisch passend. Pinsel und Zubehör können den Wert erhöhen, sofern Qualität und vorhandene Ausstattung berücksichtigt werden." },
      { id: "pflege", title: "Pflege-Adventskalender für Gesicht, Körper und Haare", answer: "Ein ausgewogener Kalender sollte nicht nur Gesichtsprodukte enthalten, wenn die Person empfindliche Haut hat. Prüfe Wirkstoffe, Parfumierung und Produktgrößen. Neue hochaktive Inhaltsstoffe sollten einzeln und nicht gleichzeitig getestet werden." },
      { id: "parfum", title: "Parfum-Adventskalender: Proben, Miniaturen und Originalgrößen", answer: "Duftproben bieten Vielfalt, Miniaturen zusätzlich Sammlerwert. Entscheidend sind Milliliterangaben und Duftfamilien. Wer nur wenige Düfte mag, fährt mit einem gezielten Discovery-Set oft besser als mit einer sehr breiten Mischung." },
      { id: "wellness", title: "Wellness-Adventskalender für entspannte Winterabende", answer: "Wellness kann Tee, Kerzen, kleine Übungen, Badezusätze oder Massageprodukte bedeuten. Achte darauf, ob die Inhalte zum Alltag und zur Wohnsituation passen. Eine Badewanne sollte beispielsweise nicht stillschweigend vorausgesetzt werden." },
      { id: "baden", title: "Bade-Adventskalender mit Badebomben, Salzen und Pflegeprodukten", answer: "Hautverträglichkeit, Duftintensität und mögliche Rückstände in der Wanne sind wichtige Kriterien. Kleine Kinder benötigen ausdrücklich geeignete Produkte. Stark gefärbte oder parfümierte Badezusätze sind für empfindliche Haut nicht automatisch die beste Wahl." },
      { id: "nagellack", title: "Nagellack-Adventskalender: Worauf kommt es an?", answer: "Vergleiche Flaschengrößen, Farbspektrum, Deckkraft und enthaltene Pflegeprodukte. Viele sehr ähnliche Rot- oder Glitzertöne verringern den praktischen Nutzen. Entferner und Unterlack sollten bei der Gesamtnutzung mitgedacht werden." },
      { id: "maennerpflege", title: "Adventskalender für Männer mit Pflege- und Grooming-Produkten", answer: "Bartpflege ist nur sinnvoll, wenn sie gebraucht wird. Universeller sind Duschpflege, Handcreme, Gesichtspflege und dezente Düfte. Hauttyp und Rasiergewohnheiten liefern eine bessere Auswahlgrundlage als die Aufschrift „für Männer“." },
      { id: "schmuck", title: "Schmuck-Adventskalender: Materialien und Qualität erkennen", answer: "Materialangaben, Verschlüsse und Nickelhinweise sind wichtiger als die Zahl der Charms. Prüfe, ob alle Teile zu einem Trägersystem gehören und nach Weihnachten kombinierbar bleiben. Vergoldet, versilbert und massiv sind unterschiedliche Qualitätsstufen." },
      { id: "socken", title: "Socken-Adventskalender: Praktisches Geschenk oder Weihnachtsgag?", answer: "Socken sind nützlich, wenn Größe, Material und Muster passen. Kontrolliere, ob einzelne Türchen ein Paar oder nur eine Socke enthalten. Baumwollanteil, Bündchen und Pflegehinweise bestimmen den langfristigen Komfort stärker als die Verpackung." },
    ],
    faq: [
      { question: "Wie berechne ich den Warenwert eines Beauty-Kalenders?", answer: "Rechne Produktgrößen auf den regulären Verkaufspreis der jeweiligen Größe um und setze nur Produkte an, die du realistisch verwenden würdest." },
      { question: "Sind Beauty-Adventskalender für Teenager geeignet?", answer: "Das hängt von Inhaltsstoffen, Farbauswahl und Hautverträglichkeit ab. Stark aktive Pflege und intensive Düfte sind nicht automatisch altersgerecht." },
      { question: "Was tun bei empfindlicher Haut?", answer: "Inhaltsstoffe vorab prüfen, neue Produkte einzeln testen und im Zweifel einen Kalender mit bekannten, reizarmen Produkten wählen." },
    ],
  },
  {
    slug: "adventskalender-hobbys-interessen",
    title: "Adventskalender für Hobbys und besondere Interessen",
    shortTitle: "Hobbys & Interessen",
    description: "Gaming, Fußball, Kochen, Heimwerken, Garten, Rätsel, Bücher und mehr: Hobby-Adventskalender passend auswählen und vergleichen.",
    kicker: "Ein gutes Geschenk spricht die Person an",
    hero: "/guides/020-spielzeug-varianten.jpg",
    heroAlt: "Adventskalender mit verschiedenen Spiel- und Hobbyartikeln",
    productIds: ["AK-0015", "AK-0018", "AK-0011"],
    buyingRules: ["Erfahrungsniveau innerhalb des Hobbys berücksichtigen.", "Kompatibilität mit vorhandener Ausrüstung oder Systemen prüfen.", "Nutzbare Inhalte höher bewerten als reine Fan-Dekoration.", "Bei Lizenzen auf Altersfreigaben und echte Produktqualität achten."],
    topics: [
      { id: "gamer", title: "Adventskalender für Gamer", answer: "Gamer-Kalender reichen von Zubehör über Sammelobjekte bis zu Rätseln. Prüfe Plattform, Spieluniversum und Altersfreigabe. Generische Schreibtischhelfer sind kompatibler, lizenzierte Inhalte persönlicher, aber nur bei einem wirklich passenden Franchise." },
      { id: "fussball", title: "Adventskalender für Fußballfans", answer: "Verein, Liga und Art des Faninteresses müssen stimmen. Karten und Sammelartikel sprechen andere Menschen an als Quiz, Fanartikel oder Trainingszubehör. Bei Kindern sollte der Tausch- und Sammelwert nicht mit garantierter Seltenheit verwechselt werden." },
      { id: "hobbykoeche", title: "Adventskalender für Hobbyköche und Feinschmecker", answer: "Das Kochniveau entscheidet: Einsteiger profitieren von Rezepten und vielseitigen Gewürzen, Fortgeschrittene von spezialisierten Zutaten oder Werkzeug. Prüfe Küchenstil, Allergien und vorhandene Ausstattung, damit keine unnötigen Doppelungen entstehen." },
      { id: "heimwerker", title: "Adventskalender für Heimwerker", answer: "Werkzeugkalender sollten ein klares System und brauchbare Materialqualität bieten. Bits, Schlüssel und Zubehör müssen zur vorhandenen Ausrüstung passen. Viele Kleinteile sind nur dann wertvoll, wenn sie später geordnet aufbewahrt und wirklich eingesetzt werden." },
      { id: "garten", title: "Adventskalender für Gartenfreunde", answer: "Saatgut, Pflanzenwissen und kleine Werkzeuge passen gut in den Winter, wenn Aussaatzeiten und Standort berücksichtigt werden. Keimfähigkeit, Sortenangaben und regionale Eignung sind wichtiger als dekorative Tütchen. Balkon und großer Garten benötigen unterschiedliche Auswahl." },
      { id: "kreative", title: "Adventskalender für Bastelfans und Kreative", answer: "Materialkalender sollten ein vollständiges Projekt oder vielseitig kombinierbare Werkstoffe liefern. Prüfe benötigte Zusatzwerkzeuge, Schwierigkeitsgrad und Zeitbedarf. Sehr kleine Materialmengen eignen sich eher zum Probieren als für fertige Arbeiten." },
      { id: "raetsel", title: "Adventskalender für Puzzle- und Rätselfans", answer: "Wähle Schwierigkeitsgrad, tägliche Spieldauer und Einzel- oder Gruppenspiel passend aus. Fortlaufende Fälle motivieren, machen aber verpasste Tage schwieriger. Bei Familien sollten Hinweise so gestaltet sein, dass mehrere Altersgruppen beitragen können." },
      { id: "buecherwuermer", title: "Adventskalender für Bücherwürmer", answer: "Neben 24 Einzeltexten gibt es Fortsetzungsgeschichten, Krimis und literarische Zitate. Genre und gewünschte Lesedauer sind entscheidend. Ein guter Buchkalender schafft jeden Tag einen abgeschlossenen Moment und bleibt trotzdem als Gesamtwerk interessant." },
      { id: "film-serien", title: "Adventskalender für Film- und Serienfans", answer: "Lizenzkalender funktionieren nur bei echter Begeisterung für das Thema. Prüfe, ob Figuren, Accessoires oder Sammlerstücke enthalten sind und ob die Qualität über reine Werbegeschenke hinausgeht. Altersfreigabe und Spoiler können relevant sein." },
      { id: "auto-motorrad", title: "Adventskalender für Auto- und Motorradfans", answer: "Modelle, Werkzeuge und Wissenskalender sprechen unterschiedliche Zielgruppen an. Maßstab, Marke, Bauaufwand und erforderliche Klebstoffe sollten vorab klar sein. Sammler legen oft mehr Wert auf Originaltreue als auf eine hohe Teilezahl." },
    ],
    faq: [
      { question: "Sind Hobby-Adventskalender auch für Anfänger geeignet?", answer: "Ja, wenn Schwierigkeitsgrad und benötigte Vorkenntnisse transparent sind. Einsteiger profitieren von Anleitungen und einem vollständigen Grundset." },
      { question: "Woran erkenne ich einen guten Rätselkalender?", answer: "An klarer Altersangabe, passender Spieldauer, nachvollziehbarem Schwierigkeitsgrad und einer Lösungshilfe, die nicht sofort alles verrät." },
      { question: "Lohnt sich ein Lizenzkalender?", answer: "Wenn Thema und enthaltene Artikel wirklich zur beschenkten Person passen. Die Lizenz allein sagt nichts über Material- oder Produktqualität aus." },
    ],
  },
  {
    slug: "adventskalender-selber-machen",
    title: "Adventskalender selber machen: Ideen, Materialien und Anleitung",
    shortTitle: "Selber machen",
    description: "DIY-Adventskalender aus Tüten, Stoff, Rollen, Gläsern und Dosen – mit praktischer Planung, nachhaltigen Materialien und Last-minute-Ideen.",
    kicker: "Persönlich, planbar und wiederverwendbar",
    hero: "/guides/016-kinder-ohne-suessigkeiten.jpg",
    heroAlt: "Selbst zusammengestellter Adventskalender mit kleinen Geschenken und Bastelmaterial",
    productIds: ["AK-0067", "AK-0056", "AK-0114"],
    buyingRules: ["Vor dem Basteln Größe und Gewicht aller Füllungen grob festlegen.", "Aufhängung und Befestigung mit ausreichender Reserve planen.", "Wiederverwendbare Grundelemente neutral gestalten und jährlich neu dekorieren.", "Bei Kindern Schnüre, Klammern und Kleinteile sicher einsetzen."],
    topics: [
      { id: "anfaenger", title: "Adventskalender selber machen: Ideen für Anfänger", answer: "Die einfachste Lösung besteht aus gleich großen Tüten oder Umschlägen, einer stabilen Aufhängung und einer begrenzten Farbwelt. Plane zuerst die Füllungen, damit jedes Behältnis groß genug ist. Ein Probeaufbau verhindert, dass Gewicht oder Abstand erst am Ende Probleme machen." },
      { id: "unter-fuenf-euro", title: "24 einfache Adventskalender-Füllungen unter fünf Euro", answer: "Kleine Snacks, Tees, Stifte, Pflegeproben, Fotos und gemeinsame Mini-Gutscheine lassen sich budgetfreundlich kombinieren. Lege ein Gesamtbudget fest und verteile stärkere Überraschungen bewusst. Persönliche Botschaften kosten wenig und schaffen oft den größten Wert." },
      { id: "partner", title: "Adventskalender für den Partner selbst befüllen", answer: "Mische nützliche Kleinigkeiten, Erinnerungen und gemeinsame Zeit. Gutscheine sollten konkret und realistisch einlösbar sein. Eine kleine Dramaturgie – etwa ruhige Werktage und gemeinsame Aktionen am Wochenende – macht den Kalender alltagstauglich." },
      { id: "kinder", title: "DIY-Adventskalender für Kinder gestalten", answer: "Wähle robuste, leicht zu öffnende Behälter und altersgerechte Inhalte. Eine fortlaufende Geschichte oder ein Bauprojekt verbindet die Türchen miteinander. Süßes kann vorkommen, muss aber nicht jeden Tag der einzige Höhepunkt sein." },
      { id: "papiertueten", title: "Adventskalender aus Papiertüten basteln", answer: "Papiertüten sind günstig und flexibel, benötigen aber bei schweren Inhalten eine stabile Leiste oder Ablage. Klammern und Schnüre sollten auf das Gesamtgewicht ausgelegt sein. Naturpapier lässt sich mit Stempeln, Zweigen oder wiederverwendbaren Anhängern dekorieren." },
      { id: "stoff", title: "Adventskalender aus Stoff nähen", answer: "Ein Stoffkalender lohnt sich über viele Jahre. Verstärke Aufhängung und Tascheneingriffe, verwende waschbare Materialien und plane unterschiedliche Taschengrößen. Eine neutrale Basis kann jedes Jahr mit neuen Bändern oder Anhängern verändert werden." },
      { id: "rollen", title: "Adventskalender aus Toilettenpapierrollen basteln", answer: "Saubere Papprollen lassen sich als Häuser, Sterne oder Baum arrangieren. Verschließe die Enden so, dass sie ohne scharfe Kanten geöffnet werden können. Das Material eignet sich für leichte Füllungen und sollte vor Feuchtigkeit geschützt bleiben." },
      { id: "glaeser-dosen", title: "Adventskalender aus Gläsern und Dosen gestalten", answer: "Gläser zeigen Inhalte und wirken hochwertig, sind aber schwer und zerbrechlich. Dosen sind robuster, benötigen jedoch entgratete Kanten und passende Deckel. Stelle beides sicher auf statt es ohne geeignete Halterung aufzuhängen." },
      { id: "ohne-muell", title: "Adventskalender ohne Verpackungsmüll selber machen", answer: "Nutze vorhandene Gläser, Stoffbeutel oder Schachteln und fülle unverpackte oder langlebige Dinge ein. Nachhaltigkeit entsteht durch wiederholte Nutzung, nicht nur durch braunes Papier. Vermeide Materialmix, der sich später schlecht trennen lässt." },
      { id: "last-minute", title: "Last-minute-Adventskalender in wenigen Stunden", answer: "Reduziere die Gestaltung auf eine Farbe, ein Behältnis und eine klare Anordnung. Digitale Gutscheine, Fotos, Nachrichten und vorhandene Lieblingssnacks sparen Einkaufszeit. Auch ein Kalender, der zunächst nur die ersten Tage vollständig enthält, kann ehrlich und stressfrei weitergeführt werden." },
    ],
    faq: [
      { question: "Wie groß sollten die Behälter sein?", answer: "Richte sie nach den größten geplanten Füllungen aus oder nutze bewusst verschiedene Größen. Vor dem Basteln hilft ein Probe-Set mit drei typischen Inhalten." },
      { question: "Wie hängt man einen schweren Kalender sicher auf?", answer: "Mit einer tragfähigen Leiste, passenden Wandbefestigungen und ausreichend Reserve. Schwere Inhalte besser aufstellen statt an einer leichten Schnur befestigen." },
      { question: "Welches Material ist am nachhaltigsten?", answer: "Am sinnvollsten ist meist das Material, das bereits vorhanden ist und viele Jahre wiederverwendet wird." },
    ],
  },
  {
    slug: "adventskalender-fuellideen",
    title: "Adventskalender befüllen: 100 Ideen für jede Zielgruppe",
    shortTitle: "Ideen zum Befüllen",
    description: "Kleine Geschenke, Gutscheine, Botschaften und Erlebnisse: Adventskalender persönlich befüllen – für Frauen, Männer, Kinder und Teenager.",
    kicker: "Kleine Inhalte mit persönlicher Wirkung",
    hero: "/guides/003-fuer-frauen.jpg",
    heroAlt: "Adventskalender mit vielfältigen kleinen Geschenken und Genussartikeln",
    productIds: ["AK-0067", "AK-0056", "AK-0114"],
    buyingRules: ["Ein Gesamtbudget festlegen und nicht jeden Tag gleich teuer planen.", "Nützliches, Genuss, Botschaften und gemeinsame Zeit ausgewogen mischen.", "Größe, Haltbarkeit und sichere Aufbewahrung vor dem Verpacken prüfen.", "Gutscheine konkret formulieren und später wirklich einlösen."],
    topics: [
      { id: "hundert-ideen", title: "100 kleine Ideen zum Befüllen eines Adventskalenders", answer: "Denke in Gruppen: Genuss, Pflege, Hobby, Alltag, Erinnerungen und gemeinsame Zeit. Aus jeder Gruppe lassen sich mehrere kleine, passende Inhalte wählen. Wiederholungen sind erlaubt, wenn sie sinnvoll sind – etwa verschiedene Tees oder mehrere Kapitel einer gemeinsamen Aktivität." },
      { id: "frauen", title: "Adventskalender-Füllungen für Frauen", answer: "Interessen sind aussagekräftiger als das Geschlecht. Tee, Bücher, Pflege, Kreativmaterial, Feinkost oder praktische Helfer können passen. Wähle nur Kosmetik oder Schmuck, wenn Vorlieben, Größen und Unverträglichkeiten bekannt sind." },
      { id: "maenner", title: "Adventskalender-Füllungen für Männer", answer: "Kaffee, Gewürze, Werkzeugzubehör, Rätsel, Pflege oder gemeinsame Aktivitäten sind mögliche Bausteine. Vermeide reine Gagartikel, wenn sie nach wenigen Minuten entsorgt werden. Eine Mischung aus Nutzwert und persönlicher Erinnerung wirkt meist stärker." },
      { id: "kinder", title: "Adventskalender-Füllungen für Kinder nach Altersgruppen", answer: "Für kleine Kinder eignen sich große Figuren, Bilder und gemeinsame Aufgaben, für Schulkinder Rätsel, Basteln und Sammelprojekte. Teenager wünschen mehr Selbstständigkeit und alltagstaugliche Inhalte. Sicherheits- und Altersangaben gelten auch bei selbst zusammengestellten Kalendern." },
      { id: "teenager", title: "Adventskalender-Füllungen für Teenager", answer: "Kleine Technikhelfer, Snacks, Pflege, Kreativmaterial, Gutscheine und gemeinsame Pläne können funktionieren. Beziehe Musik, Sport oder aktuelle Hobbys ein, ohne eine künstliche Jugendsprache zu verwenden. Qualität bei wenigen Teilen ist besser als beliebiger Kleinkram." },
      { id: "partner", title: "Persönliche Adventskalender-Füllungen für den Partner", answer: "Erinnerungsfotos, Lieblingssnacks, kleine Hilfen im Alltag und konkrete gemeinsame Termine schaffen Nähe. Verteile größere Aktionen auf Tage, an denen beide Zeit haben. Persönliche Botschaften sollten ehrlich und spezifisch sein." },
      { id: "freundinnen", title: "Kleine Geschenke für einen Freundinnen-Adventskalender", answer: "Ein geteilter Kalender oder zwölf Türchen pro Person reduziert Aufwand und bleibt persönlich. Gemeinsame Erinnerungen, Café-Gutscheine, Pflege, Snacks oder kleine Kreativideen lassen sich gut kombinieren. Gleiche vorher Budget und Erwartungen ab." },
      { id: "gutscheine", title: "Adventskalender mit Gutscheinen und gemeinsamen Erlebnissen", answer: "Gute Gutscheine nennen Aktivität, ungefähren Zeitraum und wer organisiert. Kleine Erlebnisse wie Spaziergang, Filmabend oder gemeinsames Kochen sind leichter einzulösen als große Versprechen. Plane Kosten und Termine realistisch." },
      { id: "botschaften", title: "Adventskalender mit Botschaften, Komplimenten und Erinnerungen", answer: "Schreibe konkret, was du an der Person schätzt oder woran du gern zurückdenkst. Kurze Texte wirken glaubwürdiger als allgemeine Sprüche. Einzelne Fotos, Liedtipps oder Fragen können die Botschaften abwechslungsreicher machen." },
      { id: "ohne-suesses", title: "Adventskalender-Füllungen ohne Süßigkeiten", answer: "Tee, Gewürze, Stifte, kleine Spiele, Pflege, Saatgut, Rätsel und gemeinsame Aufgaben sind gute Alternativen. Ein durchgehendes Projekt verhindert, dass 24 beliebige Kleinteile entstehen. Berücksichtige vorhandenen Besitz, um Doppelungen zu vermeiden." },
    ],
    faq: [
      { question: "Wie viel kostet ein selbst befüllter Adventskalender?", answer: "Das bestimmst du selbst. Mit Botschaften, gemeinsamen Aktivitäten und wenigen gezielten Geschenken lässt sich ein persönlicher Kalender auch mit kleinem Budget gestalten." },
      { question: "Muss jedes Türchen ein Geschenk enthalten?", answer: "Nein. Abwechselnde Botschaften, Aufgaben, Rezepte und gemeinsame Zeit machen den Kalender oft abwechslungsreicher." },
      { question: "Wie vermeide ich unnötigen Kleinkram?", answer: "Wähle ein Thema, prüfe vorhandene Dinge und bevorzuge verbrauchbare, nutzbare oder gemeinsam erlebbare Inhalte." },
    ],
  },
  {
    slug: "nachhaltige-adventskalender",
    title: "Nachhaltige Adventskalender: Materialien, Siegel und Qualität",
    shortTitle: "Nachhaltigkeit & Qualität",
    description: "Wiederverwendbare, plastikfreie, faire und regionale Adventskalender beurteilen – mit konkreten Kriterien statt grüner Werbeversprechen.",
    kicker: "Nachhaltigkeit konkret prüfen",
    hero: "/guides/027-vegan.jpg",
    heroAlt: "Pflanzenbasierter Adventskalender mit natürlichen Zutaten und wiederverwendbarer Gestaltung",
    productIds: ["AK-0056", "AK-0114", "AK-0011"],
    buyingRules: ["Wiederverwendung, Materialmenge, Inhalt und Transport gemeinsam betrachten.", "Konkrete Siegel und Herstellerangaben höher gewichten als unklare Begriffe.", "Robuste neutrale Kalender lassen sich über Jahre neu befüllen.", "Nach Gebrauch Materialien trennen, weitergeben oder sinnvoll lagern."],
    topics: [
      { id: "kriterien", title: "Nachhaltige Adventskalender: Diese Kriterien sind wirklich wichtig", answer: "Entscheidend sind Lebensdauer, Materialeinsatz, Inhalt, Herkunft und Transport. Ein aufwendiger Holzkalender ist nur dann sinnvoll, wenn er viele Jahre genutzt wird. Auch ein einfacher wiederverwendeter Stoffbeutel kann ökologisch überzeugender sein als eine neue Premiumverpackung." },
      { id: "wiederverwendbar", title: "Wiederverwendbare Adventskalender im Vergleich", answer: "Vergleiche Stabilität, Aufhängung, Taschengröße, Waschbarkeit und Reparierbarkeit. Neutrale Motive lassen sich länger verwenden. Plane auch die Lagergröße, denn ein sperriger Kalender wird seltener dauerhaft aufgehoben." },
      { id: "plastikfrei", title: "Adventskalender mit plastikfreier Verpackung", answer: "Plastikfrei beschreibt zunächst nur das Verpackungsmaterial. Papierverbunde, Beschichtungen und Einzelfolien können trotzdem enthalten sein. Frage zusätzlich nach Inhalt, Recyclingfähigkeit und unnötigen Hohlräumen." },
      { id: "bio", title: "Bio-Adventskalender: Was bedeutet das Siegel?", answer: "Bei Lebensmitteln beziehen sich Bio-Siegel auf festgelegte Produktionsstandards. Sie sagen nicht automatisch etwas über faire Löhne, Transport oder Verpackung. Prüfe das konkrete Siegel und den Anteil zertifizierter Zutaten." },
      { id: "fair", title: "Faire Adventskalender mit verantwortungsvoll produzierten Inhalten", answer: "Fairness sollte durch nachvollziehbare Standards, Lieferketteninformationen oder Zertifizierungen belegt sein. Bei Kakao, Kaffee und Tee sind Herkunft und Beschaffung besonders relevant. Allgemeine Aussagen wie „bewusst“ oder „gut“ reichen nicht aus." },
      { id: "regional", title: "Regionale Adventskalender aus Deutschland", answer: "Regional kann kurze Wege und lokale Betriebe unterstützen, muss aber konkret definiert sein. Entscheidend ist, ob Herstellung, Rohstoffe oder nur Verpackung aus der Region stammen. Direktverkauf erleichtert Rückfragen und Transparenz." },
      { id: "mogelpackung", title: "So erkennst du Mogelpackungen bei Adventskalendern", answer: "Große Außenmaße, viele Hohlräume, winzige Proben und ein unrealistischer Warenwert sind Warnzeichen. Suche nach Gewichts-, Mengen- und Größenangaben. Produktfotos sollten nicht darüber hinwegtäuschen, wie viel tatsächlich enthalten ist." },
      { id: "warenwert", title: "Warenwert eines Adventskalenders richtig berechnen", answer: "Nutze reguläre Einzelpreise und rechne Probengrößen anteilig um. Gratisproben haben nicht automatisch den Preis einer Verkaufsgröße. Verpackung und Exklusivität können einen Wert haben, sollten aber getrennt vom Produktinhalt betrachtet werden." },
      { id: "allergene", title: "Inhaltsstoffe und Allergene bei Adventskalendern prüfen", answer: "Aktuelle Zutatenlisten, Spurenhinweise und Produktkennzeichnungen sind verbindlich. Bei gemischten Kalendern muss jedes einzelne Produkt geprüft werden. Für starke Allergien ist eine direkte Herstellerbestätigung oft sinnvoll." },
      { id: "danach", title: "Was tun mit Verpackung und Resten nach Weihnachten?", answer: "Sortiere brauchbare Schachteln, Beutel und Gläser für die Wiederverwendung. Trenne Materialverbunde soweit möglich und lagere nur, was realistisch erneut genutzt wird. Ungeöffnete haltbare Inhalte lassen sich weitergeben oder spenden, sofern die Annahmestelle sie akzeptiert." },
    ],
    faq: [
      { question: "Ist ein Holz-Adventskalender immer nachhaltig?", answer: "Nein. Materialherkunft, Verarbeitung, Transport und vor allem die tatsächliche Nutzungsdauer entscheiden über die Bilanz." },
      { question: "Was bedeutet plastikfrei?", answer: "Im besten Fall bestehen Verpackung und Füllmaterial ohne Kunststoff. Der Begriff sagt aber allein noch nichts über Inhalt, Herkunft oder Recyclingfähigkeit aus." },
      { question: "Wie erkenne ich Greenwashing?", answer: "Achte auf überprüfbare Fakten, konkrete Materialien, Herkunftsangaben und anerkannte Siegel statt allgemeiner grüner Werbewörter." },
    ],
  },
  {
    slug: "geschichte-des-adventskalenders",
    title: "Geschichte und Wissen rund um den Adventskalender",
    shortTitle: "Wissen & Hintergrund",
    description: "Woher kommt der Adventskalender, warum hat er 24 Türchen und wie feiern andere Länder? Geschichte, Psychologie und kuriose Rekorde.",
    kicker: "Vom Kreidestrich zum Kultprodukt",
    hero: "/guides/010-kaufzeitpunkt.jpg",
    heroAlt: "Adventskalender zwischen herbstlichen und weihnachtlichen Elementen",
    productIds: ["AK-0001", "AK-0033", "AK-0043"],
    buyingRules: ["Historische Bräuche von modernen Verkaufsformen unterscheiden.", "Bei Rekorden und Erfinderangaben mehrere belastbare Quellen vergleichen.", "Traditionen regional und konfessionell einordnen.", "Historische Einordnung nicht als Kaufempfehlung missverstehen."],
    topics: [
      { id: "geschichte", title: "Die Geschichte des Adventskalenders", answer: "Vorläufer entstanden im 19. Jahrhundert aus häuslichen Formen des Abzählens bis Weihnachten: Kreidestriche, Bilder oder kleine religiöse Impulse. Gedruckte Kalender verbreiteten sich später und wurden zunehmend kommerziell. Schokolade und Produktminiaturen sind vergleichsweise junge Entwicklungen." },
      { id: "erfinder", title: "Wer hat den Adventskalender erfunden?", answer: "Einen einzigen Erfinder gibt es für den Brauch kaum, weil mehrere Abzähltraditionen parallel entstanden. Häufig wird Gerhard Lang mit frühen gedruckten kommerziellen Kalendern verbunden. Die historische Entwicklung ist jedoch breiter als eine einzelne Person oder Jahreszahl." },
      { id: "vierundzwanzig", title: "Warum hat ein Adventskalender 24 Türchen?", answer: "Heute zählt der Kalender meist vom ersten bis zum 24. Dezember. Der kirchliche Advent beginnt dagegen an einem Sonntag und ist nicht jedes Jahr gleich lang. Die feste Zahl folgt daher vor allem dem bürgerlichen Dezemberkalender bis Heiligabend." },
      { id: "andere-laender", title: "Adventskalender-Traditionen in anderen Ländern", answer: "Der Adventskalender ist besonders im deutschsprachigen und nordeuropäischen Raum verbreitet, wurde aber international übernommen. Lokale Weihnachtsbräuche, Geschenktermine und religiöse Traditionen unterscheiden sich. Moderne Markenprodukte ähneln sich weltweit stärker als historische Rituale." },
      { id: "luxusprodukt", title: "Vom Papierbild zum Luxusprodukt", answer: "Papierbilder und kleine Schokoladen wurden um Kosmetik, Feinkost, Spielzeug und hochpreisige Sammlerstücke erweitert. Damit verlagerte sich der Kalender vom Kinderbrauch zum saisonalen Geschenk für Erwachsene. Verpackungsdesign und Exklusivität wurden Teil des Produkts." },
      { id: "erwachsene", title: "Warum Adventskalender auch Erwachsene begeistern", answer: "Das tägliche Ritual strukturiert die Vorweihnachtszeit und verbindet Vorfreude mit einer überschaubaren Belohnung. Erwachsene schätzen außerdem Entdeckung, Nostalgie und gemeinsame Momente. Der Inhalt muss deshalb nicht kindlich sein, um dieselbe Grundidee zu erfüllen." },
      { id: "psychologie", title: "Die Psychologie hinter täglichen Überraschungen", answer: "Kleine unvorhersehbare Belohnungen erhöhen Aufmerksamkeit und Vorfreude. Gleichzeitig wirkt ein festes Ritual beruhigend und verbindend. Gute Kalender nutzen diesen Effekt, ohne künstlichen Kaufdruck oder problematische Verknappung zu erzeugen." },
      { id: "ungewoehnlich", title: "Die ungewöhnlichsten Adventskalender der Welt", answer: "Neben Miniaturkalendern gibt es begehbare Fassaden, digitale Erlebnisse, Fahrzeuge, Werkzeuge und lokale Gemeinschaftsaktionen. Ungewöhnlich ist nicht automatisch nützlich. Oft liegt der Reiz in Inszenierung, Sammeln oder gemeinsamer Teilnahme." },
      { id: "rekorde", title: "Rekorde rund um Adventskalender", answer: "Rekorde können Größe, Zahl der Türchen, Wert oder Teilnehmerzahl betreffen. Angaben verändern sich und sollten mit Datum sowie ursprünglicher Quelle genannt werden. Für eine Kaufentscheidung haben sie kaum Bedeutung, erzählen aber viel über die kulturelle Popularität." },
      { id: "fuenfundzwanzig", title: "Warum manche Adventskalender 25 Türchen haben", answer: "Ein zusätzliches Türchen bezieht den ersten Weihnachtstag ein oder folgt internationalen Geschenkgewohnheiten. Andere Kalender beginnen früher oder begleiten die gesamten Rauhnächte. Die Zahl ist daher eine Gestaltungsentscheidung und keine feste religiöse Vorschrift." },
    ],
    faq: [
      { question: "Kommt der Adventskalender aus Deutschland?", answer: "Wichtige Vorläufer und frühe gedruckte Formen stammen aus dem deutschsprachigen Raum. Der Brauch entwickelte sich jedoch aus mehreren regionalen Traditionen." },
      { question: "Gab es zuerst Schokolade oder Bilder?", answer: "Frühe verbreitete Formen arbeiteten mit Strichen, Bildern und religiösen Impulsen. Schokoladenkalender kamen später hinzu." },
      { question: "Muss ein Adventskalender 24 Türchen haben?", answer: "Nein. 24 ist die heute übliche Form bis Heiligabend, es gibt aber historische und moderne Varianten mit anderer Länge." },
    ],
  },
  {
    slug: "adventskalender-fragen-rechte-tipps",
    title: "Adventskalender: praktische Fragen, Rechte und Problemlösungen",
    shortTitle: "Praktische Hilfe",
    description: "Lieferung, Schäden, Rückgabe, Lagerung, Versand und Weihnachtsrituale: Antworten auf häufige praktische Fragen rund um Adventskalender.",
    kicker: "Wenn Bestellung oder Nutzung nicht glattlaufen",
    hero: "/guides/009-online-oder-geschaeft.jpg",
    heroAlt: "Adventskalender zwischen Versandkarton und festlichem Geschäft",
    productIds: ["AK-0002", "AK-0008", "AK-0015"],
    buyingRules: ["Beschädigungen sofort fotografieren und Händler zeitnah kontaktieren.", "Rückgabe- und Gewährleistungsfragen vom konkreten Kaufvertrag abhängig prüfen.", "Lebensmittel und Kosmetik nach Herstellerangaben lagern.", "Für Versand ausreichend Polsterung und einen stabilen Umkarton verwenden."],
    topics: [
      { id: "zu-spaet", title: "Adventskalender zu spät bestellt: die besten Alternativen", answer: "Beginne mit einem kleinen selbst gemachten Kalender für die ersten Tage und ergänze später. Digitale Botschaften, gemeinsame Aktivitäten oder ein Wochenkalender reduzieren Zeitdruck. Entscheidend ist das Ritual, nicht ein perfekter Start am ersten Dezember." },
      { id: "beschaedigt", title: "Was tun, wenn der Adventskalender beschädigt ankommt?", answer: "Dokumentiere Paket, Produkt und Etikett vor dem Öffnen weiterer Teile. Kontaktiere den Verkäufer mit Bestellnummer und klarer Beschreibung. Bei Lebensmitteln, Glas oder geöffneten Fächern sollte der Kalender bis zur Klärung nicht verwendet werden." },
      { id: "fehlend-doppelt", title: "Fehlende oder doppelte Produkte: Welche Rechte habe ich?", answer: "Weicht der Inhalt von der vereinbarten Produktbeschreibung ab, kann ein Mangel vorliegen. Sichere Fotos und Produktbeschreibung und wende dich an den Vertragspartner. Die konkrete Lösung – Ersatz, Nachlieferung oder Erstattung – hängt vom Einzelfall ab; dies ist keine Rechtsberatung." },
      { id: "rueckgabe", title: "Darf man einen geöffneten Adventskalender zurückgeben?", answer: "Bei Onlinekäufen bestehen grundsätzlich Widerrufsregeln, doch Ausnahmen können etwa für versiegelte Hygieneartikel, schnell verderbliche Ware oder geöffnete Produkte gelten. Zusätzlich kann bei Mängeln Gewährleistung greifen. Prüfe Händlerbedingungen und hole bei Streit fachlichen Rat ein." },
      { id: "lagern", title: "Adventskalender richtig lagern", answer: "Lebensmittel trocken, geruchsneutral und innerhalb der angegebenen Temperatur aufbewahren. Kosmetik vor Hitze und direkter Sonne schützen, Kerzen nicht neben Heizquellen lagern. Große Kalender sollten aufrecht und ohne Druck auf empfindliche Türchen stehen." },
      { id: "nach-weihnachten", title: "Kann man Adventskalender nach Weihnachten günstiger kaufen?", answer: "Restbestände werden häufig reduziert, aber Auswahl und Haltbarkeit sind eingeschränkt. Der Kauf für das Folgejahr eignet sich nur bei neutralem Jahresbezug und ausreichend haltbaren Inhalten. Elektronikbatterien, Kosmetik und Lebensmittel müssen passend gelagert werden." },
      { id: "oeffnen", title: "Ab wann dürfen Kinder täglich ein Türchen öffnen?", answer: "Ein festes Alter gibt es nicht. Wichtig sind ein verständliches Ritual, sichere Inhalte und Begleitung. Bei kleinen Kindern hilft eine gleichbleibende Tageszeit; verpasste oder zusätzlich geöffnete Türchen müssen nicht zum Konflikt werden." },
      { id: "verschicken", title: "Adventskalender verschicken: Verpackung, Porto und Tipps", answer: "Nutze einen stabilen Umkarton, fülle Hohlräume und schütze Ecken sowie empfindliche Inhalte. Flüssigkeiten und Glas benötigen zusätzliche Sicherung. Wiege das fertige Paket und plane Laufzeitpuffer für das saisonal hohe Versandaufkommen ein." },
      { id: "wichteln", title: "Adventskalender als Wichtelgeschenk", answer: "Für Wichtelrunden eignen sich kleine Wochenkalender, geteilte Kalender oder ein einzelnes hochwertiges Adventsprodukt. Klärt Budget und Übergabezeitpunkt vorher. Ein ganzer Kalender kann den üblichen Wichtelrahmen deutlich überschreiten." },
      { id: "ritual", title: "So wird ein Adventskalender zum Weihnachtsritual", answer: "Verknüpfe das Öffnen mit einer festen, realistischen Situation: Frühstück, Vorlesen oder Abendtee. Gemeinsame Aufmerksamkeit ist wichtiger als tägliche Perfektion. Ein wiederkehrender Kalender und kleine Familienregeln schaffen Erinnerungen über einzelne Inhalte hinaus." },
    ],
    faq: [
      { question: "Wer ist bei einem beschädigten Kalender Ansprechpartner?", answer: "In der Regel der Verkäufer, bei dem du bestellt hast. Dokumentiere den Schaden und halte Bestell- sowie Versandinformationen bereit." },
      { question: "Kann man einen Adventskalender zurückgeben?", answer: "Das hängt von Kaufart, Zustand, Inhalt und möglichen Ausnahmen ab. Prüfe die konkreten Händlerbedingungen und gesetzlichen Regeln für deinen Fall." },
      { question: "Wie lange vor Dezember sollte man verschicken?", answer: "Plane mehrere Werktage Puffer und in der Vorweihnachtszeit zusätzliche Reserve ein. Konkrete Laufzeiten hängen vom Versanddienst ab." },
    ],
  },
];

export const guideBySlug = new Map(guideClusters.map((guide) => [guide.slug, guide]));
