import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowIcon, CheckIcon } from "@/components/icons";

export const metadata: Metadata = { title: "Über Adventskalendersuche", description: "Warum Adventskalendersuche Orientierung, Transparenz und ruhige Kaufentscheidungen in den Mittelpunkt stellt.", alternates: { canonical: "/ueber-uns" } };

export default function AboutPage() {
  return <div className="page-shell about-page"><div className="container"><header className="about-hero"><div><span className="kicker">Unser Antrieb</span><h1>Wir bauen Orientierung für einen kleinen, wichtigen Moment.</h1><p>Adventskalendersuche entstand aus einer einfachen Beobachtung: Wer etwas Persönliches schenken möchte, sollte nicht zwischen hundert fast gleichen Angeboten verloren gehen.</p></div><div className="about-image"><Image src="/heroes/hero-03-paar-desktop.webp" alt="Ein Paar erlebt gemeinsam einen warmen Adventsmoment" fill sizes="(max-width: 800px) 100vw, 50vw" /></div></header><section className="values-grid"><article><span>01</span><h2>Passung vor Popularität</h2><p>Wir fragen, was zur Person passt – nicht, was gerade am lautesten beworben wird.</p></article><article><span>02</span><h2>Erklärung vor Behauptung</h2><p>Empfehlungen legen Kriterien, mögliche Nachteile und Grenzen offen.</p></article><article><span>03</span><h2>Ruhe vor Verkaufsdruck</h2><p>Keine künstliche Knappheit, keine erfundenen Siegel und keine versteckten Weiterleitungen.</p></article></section><section className="about-transparency"><div><span className="kicker">Unsere redaktionelle Haltung</span><h2>Unabhängig erklärt, affiliate-finanziert.</h2><p>Die Nutzung der Website ist kostenlos. Wenn du nach einer Empfehlung über einen gekennzeichneten Amazon-Link einkaufst, können wir eine Provision erhalten. Sie verändert deinen Preis nicht und verändert nicht die Finder-Regeln.</p><Link href="/affiliate-transparenz" className="text-link">Alle Details zur Finanzierung <ArrowIcon /></Link></div><ul className="reason-list"><li><CheckIcon />Keine bezahlte Platzierung im Match-Score</li><li><CheckIcon />Keine erfundenen Produkttests</li><li><CheckIcon />Offener Datenstand je Produkt</li><li><CheckIcon />Methodik öffentlich einsehbar</li></ul></section><div className="wide-cta"><div><span className="kicker light">Dein nächster Schritt</span><h2>Finde einen Kalender mit gutem Grund.</h2></div><Link href="/finder" className="button button-light">Finder starten <ArrowIcon /></Link></div></div></div>;
}
