import type { Metadata } from "next";
import Link from "next/link";
import { ArrowIcon, CheckIcon } from "@/components/icons";

export const metadata: Metadata = { title: "Affiliate-Transparenz", description: "So finanziert sich Adventskalendersuche durch klar gekennzeichnete Amazon-Affiliate-Links.", alternates: { canonical: "/affiliate-transparenz" } };

export default function AffiliateTransparencyPage() {
  return <div className="page-shell trust-page"><div className="container"><header className="page-intro wide"><span className="kicker">Offene Finanzierung</span><h1>Du sollst erkennen, wann wir Geld verdienen können.</h1><p>Adventskalendersuche ist kostenlos nutzbar. Die Finanzierung erfolgt über klar gekennzeichnete Amazon-Affiliate-Links.</p></header><section className="affiliate-flow"><article><span>1</span><h2>Du erhältst eine Empfehlung</h2><p>Finder-Regeln bewerten die Passung anhand deiner Antworten. Eine mögliche Provision ist kein Ranking-Kriterium.</p></article><i aria-hidden="true">→</i><article><span>2</span><h2>Du klickst bewusst</h2><p>Buttons zu Amazon tragen einen Sternchenhinweis und öffnen die externe Seite in einem neuen Tab.</p></article><i aria-hidden="true">→</i><article><span>3</span><h2>Ein Kauf kann uns finanzieren</h2><p>Als Amazon-Partner verdienen wir an qualifizierten Verkäufen. Dein Kaufpreis ändert sich dadurch nicht.</p></article></section><section className="limits-section"><div><h2>Unsere Zusagen</h2><ul className="reason-list"><li><CheckIcon />Affiliate-Links sind sichtbar gekennzeichnet.</li><li><CheckIcon />Keine versteckten Weiterleitungen.</li><li><CheckIcon />Keine bezahlte Platzierung im Finder.</li><li><CheckIcon />Keine künstliche Verknappung.</li></ul></div><div><h2>Amazon-Partner-ID</h2><p>Die aktuell in den Produktlinks verwendete Partner-ID lautet <code>onlinestarkei-21</code>. Preise, Lieferbarkeit und Produktinformationen auf Amazon können sich ändern. Verbindlich ist immer die Anzeige auf der Amazon-Produktseite.</p><p>„Amazon“ und alle damit verbundenen Kennzeichen sind Marken von Amazon.com, Inc. oder verbundenen Unternehmen.</p></div></section><section className="transparency-note"><h2>Warum wir keine Produktbilder von Amazon kopieren</h2><p>Diese Website verwendet eigene redaktionelle Kategoriesymbole. Amazon-Produktbilder werden weder heruntergeladen noch verändert. Eine spätere Nutzung dynamischer Produktmedien darf nur über einen zulässigen, aktuell konfigurierten Amazon-Partnerzugang erfolgen.</p><Link href="/methodik" className="text-link">Zur Empfehlungslogik <ArrowIcon /></Link></section></div></div>;
}
